### PR TITLE
Keep container running on `docker-compose up`

### PR DESCRIPTION
**Pull request by teneightfive**
Fixes an issue with a newer version of docker-compose: https://github.com/docker/compose/issues/1193

### CODE REVIEW

**Comment by SteveMarshall** [comment]
Test this please

**Comment by SteveMarshall** [comment]
As discussed, this doesn't yet work for me: it complains of a missing `mtp_api` database. Can we make it so that `docker-compose up` creates that? (I think @marcofucci is looking at that?)

**Comment by marcofucci** [comment]
Well, I think the db problem belongs to a different branch/PR so we should merge this.

**Comment by SteveMarshall** [comment]
@marcofucci Agreed; done.

**Pull request merged**
