### PR TITLE
Include date on which a credit was set manual in API response

### PR DESCRIPTION
**Pull request by ibrechin**
(if it ever was)

### CODE REVIEW

**Comment by ibrechin** [comment]
retest this please

**Comment by ibrechin** [comment]
retest this please

**Comment by ibrechin** [comment]
retest this please

**Comment by ibrechin** [comment]
retest this please

**Comment by ibrechin** [comment]
retest this please

**Comment by ibrechin** [comment]
retest this please

**Comment by ushkarev** [comment]
retest this please

**Comment by ushkarev** [comment]
retest this please

**Comment by ushkarev** [comment]
retest this please

**Comment by ibrechin** [comment]
retest this please

**Comment by ibrechin** [comment]
retest this please

**Pull request merged**
