### PR TITLE
Add createdb instructions to README

### PR DESCRIPTION
**Pull request by marcofucci**
I've tried to find an easy / clear way of doing this using docker-compose.

### CODE REVIEW

**Comment by marcofucci** [comment]
@SteveMarshall what do you think?

**Comment by SteveMarshall** [comment]
Is there a reason we can't just set the `POSTGRES_DB` environment variable and [let the entry point set up the `mtp_api` DB](https://github.com/docker-library/postgres/blob/master/9.4/docker-entrypoint.sh#L64)?

If that doesn't work, I can't see any reason not to use the default `postgres` DB. As the docs say, it's “meant for use by users, utilities and third party applications”, and this is only for local development (and maybe testing on Jenkins), so we should just be able to make `mtp_api/settings/base.py` call `os.environ.get('DB_NAME', 'mtp_api')`, and pass that in the `docker-compose.yml` like we do for host, port, and so on.

**Comment by marcofucci** [comment]
@SteveMarshall that might work but you need to delete the postgres dbdata image and test it as the docker_entrypoint.sh really executes only ones.

I will leave this to you as it's not high priority for now and I'd rather focus on other things.

**Comment by SteveMarshall** [comment]
I've tackled using the default postgres container DB in #16, so closing this.

**Pull request closed without merging**
